version: 2.1
jobs:
  build:
    macos:
      xcode: "11.3.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec fastlane test
      - run: bundle exec fastlane adhoc