version: 2.1
jobs:
  unit_test:
    macos:
      xcode: 12.1.0
    environment:
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - restore_cache:
          key: framework-cocoapods-{{ checksum "Podfile.lock" }}
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_test_results:
          path: output/scan
      - save_cache:
          key: framework-cocoapods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods

  build_example:
    macos:
      xcode: 12.1.0
    environment:
      FASTLANE_LANE: build_example
    steps:
      - checkout
      - run: bundle install
      - restore_cache:
          key: example-cocoapods-{{ checksum "Example/Podfile.lock" }}
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_test_results:
          path: output/scan
      - save_cache:
          key: example-cocoapods-{{ checksum "Example/Podfile.lock" }}
          paths:
            - Example/Pods
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - derived_data
            - output

  ui_test:
    macos:
      xcode: 12.1.0
    environment:
      FASTLANE_LANE: ui_test
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: example-cocoapods-{{ checksum "Example/Podfile.lock" }}
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - save_cache:
          key: example-cocoapods-{{ checksum "Example/Podfile.lock" }}
          paths:
            - Example/Pods
      - store_test_results:
          path: output/scan

  browserstack:
    macos:
      xcode: "12.1.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - attach_workspace:
          at: /tmp/workspace
      - run: bundle exec fastlane browserstack

workflows:
  build:
    jobs:
      - unit_test
      - build_example
      - ui_test:
          requires:
            - build_example
      - browserstack:
          requires:
            - build_example